---
apiVersion: v1
kind: Service
metadata:
  name: color2
  namespace: faces
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    service: color2
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color2
  namespace: faces
spec:
  selector:
    matchLabels:
      service: color2
  template:
    metadata:
      labels:
        service: color2
    spec:
      containers:
      - env:
        - name: FACES_SERVICE
          value: color
        - name: COLOR
          value: blue
        - name: DELAY_BUCKETS
          value: 0,5,10,15,20,50,200,500,1500
        image: ghcr.io/buoyantio/faces-workload:1.0.0
        imagePullPolicy: Always
        name: color2
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      restartPolicy: Always
