---
apiVersion: v1
kind: Service
metadata:
  name: smiley2
  namespace: faces
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    service: smiley2
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smiley2
  namespace: faces
spec:
  selector:
    matchLabels:
      service: smiley2
  template:
    metadata:
      labels:
        service: smiley2
    spec:
      containers:
      - env:
        - name: FACES_SERVICE
          value: smiley
        - name: SMILEY
          value: HeartEyes
        - name: DELAY_BUCKETS
          value: 0,5,10,15,20,50,200,500,1500
        image: ghcr.io/buoyantio/faces-workload:1.0.0
        imagePullPolicy: Always
        name: smiley2
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      restartPolicy: Always
